name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:

      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        run: docker login --username=${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }} crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com

      - name: Build Image
        run: |
          buildx build -t crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/liudur/onekvm \
            --progress plain \
            --platform linux/amd64,linux/arm64,linux/arm/v7  \
            --build-arg CACHEBUST=$(date +%s) \
            -f build/Dockerfile . \
            --push